# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -extldflags "-static"
  flags:
  - -trimpath
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
