{
 "title": "NextDNS",
 "tags": [ "nextdns" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "profile", "query": { "query": "label_values(profile)" } }
  ]
 },
 "panels": [
  {
   "title": "All Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nextdns_queries_total", "legendFormat": "All" }
   ]
  },
  {
   "title": "Domains",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextdns_blocked_queries", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Devices",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextdns_device_queries", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Blocked Queries %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "$blocked / $total\n",
     "type": "math"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nextdns_queries_total[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "nextdns_type_queries", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "nextdns_blocked_queries_total", "legendFormat": "Blocked" }
   ]
  },
  {
   "title": "IP Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "nextdns_ip_version_queries", "legendFormat": "IPv{{version}}" }
   ]
  }
 ]
}